import type { Prospect, ProspectDiagnosis } from '../types';

function sanitizeInternalNotes(internalNotes?: string) {
  if (!internalNotes?.trim()) return undefined;

  const lowered = internalNotes.toLowerCase();
  const blockedTokens = [
    'token',
    'secret',
    'password',
    'credencial',
    'private',
    'interno confidencial',
  ];

  if (blockedTokens.some((token) => lowered.includes(token))) {
    return undefined;
  }

  return internalNotes.length > 900
    ? `${internalNotes.slice(0, 900)}...`
    : internalNotes;
}

export function serializeDiagnosisForPrompt(diagnosis: ProspectDiagnosis, publicUrl?: string | null) {
  return {
    title: diagnosis.title,
    summary: diagnosis.summary,
    markdown: diagnosis.markdown,
    structured: diagnosis.structured,
    scores: diagnosis.scores,
    publicNotes: diagnosis.publicNotes,
    status: diagnosis.status,
    slug: diagnosis.slug,
    visibility: diagnosis.visibility,
    publicUrl: publicUrl || null,
  };
}

export function serializeProspectForPrompt(prospect: Prospect) {
  return {
    id: prospect.id,
    name: prospect.name,
    category: prospect.category,
    city: prospect.city,
    country: prospect.country,
    phones: prospect.phones,
    website: prospect.website,
    instagram: prospect.instagram,
    facebook: prospect.facebook,
    address: prospect.address,
    sourceUrls: prospect.sourceUrls,
    evidenceNotes: prospect.evidenceNotes,
    internalNotes: sanitizeInternalNotes(prospect.internalNotes),
    rawDiscovery: prospect.rawDiscovery,
    normalizedCandidate: prospect.normalizedCandidate,
    providerIntelligence: prospect.providerIntelligence,
    importProjection: prospect.importProjection,
    scores: prospect.scores,
    signals: prospect.signals,
  };
}

export function buildSlidesResearchContext(prospect: Prospect, publicUrl?: string | null) {
  return [
    'Actúa como senior product engineer, estratega de conversión, editor de marca y director creativo editorial de El Ojo Negro.',
    'También actúa como arquitecto de percepción obsesionado con claridad, confianza, ruta de decisión y deseo de avanzar sin exageración.',
    '',
    'Voy a darte toda la información disponible de un prospecto y un diagnóstico ya generado. Tu tarea es investigar profundamente la marca y producir un entregable final de exactamente 4 slides listos para compartir con el prospecto.',
    'No quiero slides que resuman presencia digital. Quiero slides que revelen si esa presencia ayuda a decidir.',
    'La reacción ideal del prospecto al verlas debe ser: “Vieron algo que yo no estaba viendo; necesito ordenar esto con ellos”.',
    'Eso no se logra con humo. Se logra con investigación real, criterio visual alto, copy elegante y una lectura que haga sentir claridad, tensión comercial sobria y dirección.',
    '',
    'Este material será compartido con el prospecto, por lo tanto:',
    '- no uses lenguaje agresivo,',
    '- no inventes métricas,',
    '- no afirmar pérdidas comerciales,',
    '- no hagas afirmaciones no verificadas,',
    '- si algo no se puede confirmar, trátalo como hipótesis o evita afirmarlo,',
    '- mantén un tono elegante, útil, claro y accionable.',
    '- no busques impresionar con exageración; impresiona con precisión, criterio y valor.',
    '- usa solo observaciones prudentes basadas en fuentes públicas.',
    '',
    'Investiga profundamente usando prioritariamente las URLs y fuentes ya provistas:',
    '- website oficial',
    '- Instagram oficial',
    '- otras fuentes públicas visibles si están referenciadas',
    '- colores de marca',
    '- logo',
    '- identidad visual',
    '- tono de comunicación',
    '- propuesta visible',
    '- estilo fotográfico o estético',
    '- consistencia entre web, Instagram y otros activos',
    '- señales de claridad, confianza, conversión y experiencia mobile',
    '- percepción de nivel premium o no premium',
    '- qué parte de la experiencia transmite autoridad y qué parte introduce fricción',
    '- qué promesa comercial parece fuerte y cuál parece difusa',
    '- qué tan clara o dispersa se siente la ruta de decisión entre web, Instagram, Google, directorios, landing y WhatsApp',
    '- qué tan corta o larga parece la distancia entre interés y contacto',
    '',
    'Si encuentras identidad visual clara, úsala.',
    'Si no logras verificar logo o colores con certeza, aproxima con sobriedad sin inventar atributos falsos.',
    'Si la marca tiene una estética débil, no la humilles ni la contradigas: elévala con elegancia usando lo que sí es verificable.',
    'No diagnostiques si la marca existe. Diagnostica si su presencia ayuda a decidir, confiar, recordar y escribir.',
    '',
    'Datos del prospecto:',
    JSON.stringify(serializeProspectForPrompt(prospect), null, 2),
    '',
    'Diagnóstico base:',
    JSON.stringify(serializeDiagnosisForPrompt(prospect.diagnosis, publicUrl), null, 2),
  ].join('\n');
}

export function buildSlidesDeckStructure() {
  return [
    'Tu salida final debe ser un deck de exactamente 4 slides, no más y no menos.',
    'No entregues una lista de ideas sueltas.',
    'No entregues solo análisis.',
    'No entregues un documento largo.',
    'No entregues 5 slides.',
    'No entregues texto sin estructura visual.',
    'Genera el contenido final de 4 slides.',
    'Cada slide debe sentirse como una pieza final de alto nivel, no como borrador ni como outline operativo.',
    'La secuencia completa debe crear una progresión emocional y comercial: lectura estratégica → validación de base → fricción invisible → sprint recomendado.',
    '',
    'Estructura exacta de las 4 slides:',
    '',
    'Slide 1 — Portada + lectura ejecutiva',
    '- Nombre del prospecto',
    '- Título del diagnóstico',
    '- Subtítulo elegante',
    '- Lectura ejecutiva corta con visión de negocio, no inventario',
    '- Branding visual del prospecto',
    '- Firma sutil: Diagnóstico por El Ojo Negro',
    '- Debe reconocer la base existente sin sonar complaciente',
    '- Debe abrir con presencia visual suficiente para que el prospecto sienta que esto fue pensado específicamente para su marca',
    '- Debe dejar clara la oportunidad principal: ordenar percepción, confianza y ruta de decisión',
    '',
    'Slide 2 — Lo que ya está bien + lectura actual',
    '- Señales positivas observadas',
    '- Scores o lectura visual resumida si aportan y no distraen',
    '- Qué transmite hoy la presencia digital y por qué eso importa comercialmente',
    '- Dónde ya existe base valiosa para confianza, diferenciación o descubrimiento',
    '- Mantener tono positivo, preciso y nada complaciente',
    '- Debe hacer que el prospecto sienta: “Sí, entendieron mi marca y vieron algo real”',
    '',
    'Slide 3 — Oportunidades principales',
    '- 3 oportunidades visibles de mejora',
    '- Cada una debe hablar de fricción en la ruta de decisión, no de mejoras genéricas',
    '- Cada una con: observación, tensión comercial elegante y movimiento recomendado',
    '- No usar lenguaje acusatorio',
    '- No afirmar pérdidas como hecho',
    '- Las oportunidades deben sentirse accionables y valiosas, no genéricas',
    '- Debe aparecer explícitamente la idea de distancia entre interés y contacto cuando aplique',
    '',
    'Slide 4 — Ruta recomendada + siguiente paso',
    '- Sprint recomendado, no venta desesperada',
    '- Presenta un sprint corto de claridad y conversión digital, sprint de percepción y ruta de decisión, sprint mobile-first o sprint para ordenar propuesta, confianza, servicios y CTA',
    '- Sistema mínimo recomendado',
    '- Ruta visual: Instagram/Google → Landing/Servicio → Confianza → WhatsApp → Agenda/Seguimiento',
    '- Explica por qué ese sprint tiene sentido ahora',
    '- CTA final sobrio: Si esto hace sentido, el siguiente paso es convertir la presencia actual en una ruta de decisión más clara.',
    '- Debe cerrar con suficiente claridad y deseo como para que el prospecto quiera conversar',
  ].join('\n');
}

export function buildSlidesOutputInstructions() {
  return [
    'Requisitos visuales:',
    '- usar colores de la marca del prospecto como base',
    '- usar logo si es verificable desde fuentes públicas',
    '- usar una estética limpia, premium, sobria y editorial',
    '- evitar saturación',
    '- jerarquía impecable',
    '- máximo enfoque en claridad',
    '- diseño pensado para verse bien como slides compartibles',
    '- mantener consistencia visual entre las 4 slides',
    '- si la identidad de marca del prospecto es débil, usar una adaptación elegante sin traicionar su estética pública',
    '- no usar layouts genéricos de consultora barata ni recursos visuales vacíos',
    '- el deck debe verse inevitable, específico y hecho a medida para esta marca',
    '- priorizar composición, ritmo, contraste, espacio negativo y foco narrativo',
    '- si propones imágenes o texturas, deben reforzar percepción premium y no distraer del argumento',
    '- cada slide debe ser legible en mobile y no depender de párrafos eternos',
    '',
    'Requisitos de lenguaje:',
    '- escribir en español',
    '- mantener tono consultivo y premium',
    '- evitar lenguaje agresivo',
    '- no decir “están perdiendo clientes” como hecho',
    '- no afirmar pérdidas comerciales',
    '- no decir “tu negocio está fallando”',
    '- priorizar claridad comercial, confianza, conversión a WhatsApp, experiencia mobile y consistencia digital',
    '- usar lenguaje como: se observa, hay una oportunidad visible, podría mejorar, ruta más clara, esto puede reducir la distancia entre interés y contacto, el siguiente movimiento recomendado sería',
    '- si algo no es verificable, no inventarlo',
    '- evita exageración marketinera, clichés y promesas infladas',
    '- cada frase debe poder compartirse con el prospecto sin incomodidad ni sensación de ataque',
    '- no sonar como auditoría técnica, reporte SEO ni plantilla de consultoría genérica',
    '- cada slide debe sentirse más como arquitectura de percepción que como resumen de presencia digital',
    '',
    'Modo de respuesta obligatorio:',
    '- responde como AI textual, no como AI de análisis abierto',
    '- tu respuesta final debe ser únicamente el deck textual final de 4 slides',
    '- no entregues introducción',
    '- no entregues explicación metodológica',
    '- no entregues notas previas',
    '- no entregues observaciones aparte',
    '- no entregues un quinto bloque final',
    '- no entregues recomendaciones fuera de los 4 slides',
    '',
    'Formato final esperado y obligatorio:',
    'Debes responder exactamente con esta estructura y con estos 4 bloques, sin agregar otros:',
    '',
    'SLIDE 1',
    'Título:',
    'Objetivo de la slide:',
    'Copy final:',
    'Estructura visual:',
    'Elementos visuales sugeridos:',
    'Notas de identidad visual aplicadas:',
    '',
    'SLIDE 2',
    'Título:',
    'Objetivo de la slide:',
    'Copy final:',
    'Estructura visual:',
    'Elementos visuales sugeridos:',
    'Notas de identidad visual aplicadas:',
    '',
    'SLIDE 3',
    'Título:',
    'Objetivo de la slide:',
    'Copy final:',
    'Estructura visual:',
    'Elementos visuales sugeridos:',
    'Notas de identidad visual aplicadas:',
    '',
    'SLIDE 4',
    'Título:',
    'Objetivo de la slide:',
    'Copy final:',
    'Estructura visual:',
    'Elementos visuales sugeridos:',
    'Notas de identidad visual aplicadas:',
    '',
    'No uses encabezados distintos.',
    'No cambies la cantidad de slides.',
    'No sustituyas SLIDE 1, 2, 3 o 4 por otro formato.',
    'No entregues JSON.',
    'No entregues Markdown libre.',
    'No entregues un outline.',
    'No entregues una lista de ideas.',
    'Entrega únicamente el contenido final de esas 4 slides.',
    '- en modo textual, no seas abstracto: especifica jerarquía, distribución, énfasis visual, tono de titulares y rol de cada elemento',
    '- en Copy final evita bullets innecesarios; privilegia bloques cortos, tensión clara y lectura mobile-first',
    '',
    'Barra de calidad obligatoria:',
    '- si el resultado parece plantilla, reházalo mentalmente antes de entregarlo',
    '- si el resultado podría servirle igual a cualquier otro negocio, reházalo',
    '- si el resultado no genera deseo de conversar, reházalo',
    '- si las slides solo describen presencia digital y no explican cómo esa presencia ayuda o no ayuda a decidir, reházalo',
    '- quiero 4 slides que se sientan como un diagnóstico premium, compartible y comercialmente inevitable',
    '- si tu respuesta no termina siendo exactamente 4 slides, considera que fallaste la tarea',
  ].join('\n');
}

export function buildSlidesGenerationPrompt(
  prospect: Prospect,
  options?: { publicUrl?: string | null },
) {
  const publicUrl = options?.publicUrl ?? null;

  return [
    buildSlidesResearchContext(prospect, publicUrl),
    '',
    buildSlidesDeckStructure(),
    '',
    buildSlidesOutputInstructions(),
  ].join('\n\n');
}
